// Complete job listings data extracted from the backup
export const allJobListingsFromBackup = [
  {
    id: '0bb7dd12-d2df-4041-8cdb-b1a5193741f7',
    organizationId: 'org_30ST7Ki6gsBHZFdzcSxntYgBdiY',
    title: 'Next Js Developer',
    description: '**Must Have Skills:**\n\n• NextJS, Sitecore XM Cloud, Tailwind CSS,\n\n• .NET NextJS is mandatory skill requirement.\n\n**Nice to Have Skills:**\n\n• Experience with GitHub Copilot,Shift-Left\n\n• Testing on TypeScript and DevOps (CI/CD Pipeline)\n**Detailed Job Description:**\n\nTo work closely with client as a web developer for clients ongoing project where they are rebuilding and migrating their internal app to a new tech (NextJS)\n\n**Top 2 responsibilities**\n\n• Web development using NextJs;\n\n• Experience with Website Maintenance and Enhancements\n\n• Collaborate closely with client stakeholders',
    wage: 65000,
    wageInterval: 'yearly',
    stateAbbreviation: 'VIC',
    city: 'Melbourne',
    isFeatured: false,
    locationRequirement: 'in-office',
    experienceLevel: 'junior',
    status: 'published',
    type: 'full-time',
    postedAt: '2025-07-27 12:40:09.756+00',
    createdAt: '2025-07-27 12:40:01.970375+00',
    updatedAt: '2025-07-27 12:40:09.756+00'
  },
  {
    id: '7c032855-64a6-4aa8-be00-7931858176f8',
    organizationId: 'org_30ST7Ki6gsBHZFdzcSxntYgBdiY',
    title: 'Technical Business Analyst',
    description: 'Senior Technical Business Analyst with 8 years of experience.\n\n• Driving the achievement of clients strategy by working with stakeholders as directed to elicit,\n\nanalyze, test/adjust, communicate, validate and manage requirements for changes to systems,\n\nbusiness processes, policies, information and data.\n\n• Managing requirements through the delivery lifecycle to meet business needs.\n\n• Providing recommendations for process redesign and improvements and\n\nbusiness solutions, enabling changes to processes, policy and/or information.\n\n• Supporting the wider project/ program team on key change activities to\n\nensure change is embedded sustainably.\n\n• Work with business and technical stakeholders to gather and document\n\ndetailed requirements and often translating this into technical specifications.\n\n• Effectively communicating with both technical and non-technical\n\nstakeholders throughout the project lifecycle\n\n• Collaborate with Solution Designer, and Development Team to ensure\n\nseamless integration of the platform.\n\n• Facilitate workshops and conduct impact assessments\n\n• Define and maintain user stories and process flows.\n\n• Support UAT for enhancements or migrations.\n\n• Review Test Cases/Scenarios\n\nNice to have skills:\n\nAS, R-Programming, Python, Big Data, Hadoop',
    wage: 80000,
    wageInterval: 'yearly',
    stateAbbreviation: 'NSW',
    city: 'Sydney',
    isFeatured: false,
    locationRequirement: 'in-office',
    experienceLevel: 'junior',
    status: 'published',
    type: 'full-time',
    postedAt: '2025-07-27 12:40:48.751+00',
    createdAt: '2025-07-27 12:40:45.122257+00',
    updatedAt: '2025-07-27 12:40:48.751+00'
  },
  {
    id: '66ee26f5-f8fe-4bbc-a6a8-2f38f989f5fe',
    organizationId: 'org_30SRX5mn4qsXRUeA59ejawEIJxH',
    title: 'Settlement Analyst',
    description: '**Maple Asset Finance** is seeking an experienced **Settlement Analyst** to join our dynamic team. We\'re looking for someone with a background in **commercial asset finance**, a sharp eye for detail, and a passion for delivering exceptional customer outcomes. This is a high-impact role suited to professionals who thrive in a fast-paced environment and are ready to contribute to a growing business.\n\n**What You\'ll Do:**\n\n* Accurately process settlements in a timely manner\n* Verify settlement conditions and manage applications through to payment disbursement\n* Communicate clearly and professionally with brokers and internal teams\n* Identify and manage fraud risks and document execution issues\n* Assess supplier risk and ensure data quality across applications\n* Ensure compliance with AML/CTF policies and internal procedures\n* Support operational tasks and contribute to continuous process improvement\n\n**What You Bring:**\n\n* Bachelor\'s degree in Commerce, Finance, Accounting, or Law (preferred)\n* Minimum 1 year of experience in a settlements or similar operational role\n* Prior experience in SME or commercial asset finance lending (advantageous)\n* Strong analytical and critical thinking skills with sound risk judgement\n* High attention to detail and ability to multitask effectively\n* Excellent written and verbal communication skills\n* Customer-focused with a proactive and collaborative approach\n\n**Why Join Us?**\n\n* **Driven Team:** Be part of a high-performance team focused on achieving results.\n* **Flexibility and Trust:** At Maple, we offer the flexibility to manage your work in a way that suits your goals, with the trust that you\'ll deliver results. We empower you to take ownership of your role and approach your work in a way that maximizes your success.\n* **Make an Impact & Grow with Us:** This is a unique opportunity to contribute directly to the development of our business and grow as we continue to scale. You\'ll have the potential to expand your role and advance your career as the organization evolves.\n\n**About Maple**\n\nMaple is an independent asset finance lender committed to reshaping the commercial finance experience. We believe in building strong partnerships and making it easy to do business. Our culture is collaborative, fast-moving, and focused on results.\n\n**Apply now and take your career to the next level with an industry leader in asset finance!**',
    wage: 85000,
    wageInterval: 'yearly',
    stateAbbreviation: 'NSW',
    city: 'Sydney',
    isFeatured: false,
    locationRequirement: 'hybrid',
    experienceLevel: 'junior',
    status: 'published',
    type: 'full-time',
    postedAt: '2025-07-27 12:41:09.153+00',
    createdAt: '2025-07-27 12:30:56.888413+00',
    updatedAt: '2025-07-27 12:41:09.153+00'
  },
  {
    id: '0dd2000c-3c7f-4be2-9c65-c9c1244d4559',
    organizationId: 'org_30SdGqAliowJDUBi3Gfy1z3Nbxx',
    title: 'Python Engineer & Generative AI',
    description: 'Are you a Python engineer with a passion for generative AI? Do you dream of building something extraordinary and seeing it make a real impact at leading companies? We\'re looking for someone like you – an ambitious coder who thrives on innovation, rapid growth, and tackling big challenges in a fun, supportive environment.\n\nAs a mid-level **Python Engineer (Generative AI)** at Enterprise AI Group, you\'ll work at the intersection of software development and machine learning. Your code will directly contribute to our intelligent SaaS platform, helping major organisations harness AI to **drive efficiency, enhance customer engagement, and turn data into actionable insights**. In short, you\'ll play a key role in our mission to bring AI into real-world workflows quickly and safely, transforming how businesses operate with cutting-edge tech.\n\n**What you\'ll be doing**\n\n* **Full-time, 5 days onsite (Martin Place, Sydney).** We iterate face-to-face to outpace competitors.\n* Build new features and RESTful APIs using Python (FastAPI) to expand our generative AI platform\'s capabilities.\n* Develop and fine-tune AI-driven services using large language models.\n* Leverage Azure\'s AI ecosystem: integrate **Azure OpenAI, Cognitive Search, and data services** into our products, and connect our platform with client systems via APIs.\n* Optimise our AI pipelines for scalability: work with **MongoDB/Cosmos DB** and vector databases to handle big data efficiently.\n* Collaborate closely with a tight-knit team of engineers and data scientists, rapidly prototyping ideas (Monday brainstorm to Friday demo is how we roll!) and delivering improvements that wow our customers.\n\n**What we\'re looking for**\n\nMust-haves:\n\n* **Strong Python skills:** You\'ve built backend applications or APIs (FastAPI or similar) and can write clean, efficient code.\n* **AI/ML enthusiasm:** Hands-on experience with machine learning or generative AI (NLP, large language models) – you\'ve maybe played with GPT APIs and can show us your projects in Github\n* **Problem-solving mindset:** Love tackling complex problems and debugging; you\'re logical, curious, and resourceful.\n* **Team player:** Great communication skills and **collaborative spirit** – you thrive in a team, sharing ideas and building solutions together.\n* **BS/MS in CompSci (or equivalent experience):** A solid foundation in CS principles and the ability to learn new tech quickly.\n\n**Nice-to-haves:**\n\n* **Node.js or Full-Stack:** Some experience with Node or front-end frameworks (React/Next.js) – we appreciate versatility.\n* **Azure/cloud experience:** Familiarity with Azure AI Services, Azure ML, or cloud infrastructure (Azure DevOps, Bicep/Terraform) is a big plus.\n* **Search/DB expertise:** Experience with search engines or graph/vector databases for semantic search.\n* **Certifications:** Azure or AI certifications, or any cool **open-source AI projects** you\'ve contributed to – show off your passion!\n\n**What we offer**\n\n* **Salary:** A$95K – A$120K + ESOP (employee stock ownership plan).\n* **Career growth:** Fast-track progression in a scaling startup – we\'ll support your development into senior roles as we grow.\n* **Culture & Diversity:** A dynamic, fun, **inclusive** workplace – no egos, no old-school corporate vibe. We celebrate diversity and everyone\'s ideas matter.\n* **Tech & Innovation:** Work with the latest tech (see *Our Tech Stack* below) on challenging projects. Your ideas turn into features **without red tape** – *ideas on Monday, prototypes by Friday* is how we operate.\n* **Impact:** **Your decisions power mission-critical AI workflows for tier-one clients.** You\'ll see the direct results of your work in real businesses every day.\n* **Speed & support:** Quick, candidate-friendly hiring process (we won\'t leave you hanging). Expect mentorship, hackathons, and a team that\'s got your back from day one.\n\n**Our Tech Stack**\n\n* **Backend:** Python, FastAPI\n* **Databases & AI:** MongoDB, Cosmos DB, vector & graph DBs\n* **Cloud:** Azure (everything)\n* **Frontend:** Next.js, TypeScript, PayloadCMS\n\n**About us**\n\n**Enterprise AI** is a Sydney-based AI startup delivering cutting-edge generative AI solutions on a SaaS platform so clients get results faster. We bridge AI theory with real-world impact, helping enterprises stay ahead of the competition with data-driven, scalable technology. Founded in 2024, we\'re already partnering with major players (like Microsoft) and serving **government and top-tier industries** with our AI products. Our team culture is high-energy, collaborative, and innovative – we move fast, learn faster, and have fun doing it.\n\nSend your CV or LinkedIn profile to **talent@enterpriseaigroup.com** – we usually reply within 48 hours.',
    wage: 110000,
    wageInterval: 'yearly',
    stateAbbreviation: 'NSW',
    city: 'Sydney',
    isFeatured: false,
    locationRequirement: 'in-office',
    experienceLevel: 'junior',
    status: 'published',
    type: 'full-time',
    postedAt: '2025-07-27 14:01:30.513+00',
    createdAt: '2025-07-27 14:01:24.359942+00',
    updatedAt: '2025-07-27 14:01:30.514+00'
  },
  {
    id: '2c8a486f-4a6f-4d90-b497-a4e3e9b6cc6f',
    organizationId: 'org_30SdGqAliowJDUBi3Gfy1z3Nbxx',
    title: 'React / Next.js Engineer – Generative AI SaaS',
    description: 'Mid-level React & Next.js Engineer for a Generative AI SaaS startup in Sydney! Full-time onsite role building cutting-edge AI-powered features in a dynamic environment. You\'ll join a small, high-energy team embedding generative AI into real-world enterprise workflows. We iterate face-to-face (5 days a week in our Martin Place office) to outpace competitors, so your ideas go from whiteboard to production fast. You\'ll take ownership of core front-end features and see your work make a **huge impact** on business users every day.\n\n**What you\'ll be doing**\n\n* **Building** sleek, responsive UIs with React, Next.js and TypeScript to deliver new AI-driven features\n* **Integrating** our front-end with backend APIs and OpenAI GPT-4 services to create seamless generative AI experiences\n* **Collaborating** closely with designers and product managers to shape an intuitive UX for complex enterprise workflows\n* **Optimising** performance and reliability – ensuring our app is snappy and secure for thousands of users\n* **Iterating** rapidly: prototyping ideas, testing with users, and shipping improvements in an agile, continuous delivery environment\n* **Contributing** your insights to product direction – we value team members who speak up and drive innovation\n\n**What we\'re looking for**\n\n**Must-haves:**\n\n* 3+ years of hands-on experience building modern front-end applications with **React.js** and **Next.js** (including SSR)\n* Strong proficiency in **JavaScript/TypeScript**, HTML5/CSS3, and front-end tooling\n* Experience consuming RESTful APIs or GraphQL, and understanding of web app architecture (client/server)\n* A knack for problem-solving and writing clean, maintainable code (you love to **ship** well-tested features)\n* Great communication and teamwork skills – you enjoy brainstorming in person and iterating quickly with others\n* **Sydney-based** with full working rights in Australia (this role is 100% on-site; we do not offer visa sponsorship)\n* Passion for generative AI and eagerness to learn AI integration – you\'re excited about what tools like GPT can do for users. We would love to see your github repo, about what you are passionate about\n\n**Nice-to-haves:**\n\n* Familiarity with **Node.js** or backend development (on Next.js functions and APIs)\n* Exposure to **AI/ML** frameworks or APIs (e.g. OpenAI, TensorFlow) – any hackathon or side-project with GPT models is a plus\n* Experience at a startup or in a fast-paced product team where you\'ve worn multiple hats\n* Knowledge of modern front-end styling and build tools (Tailwind CSS, webpack, etc.)\n* Understanding of cloud platforms like **AWS** and CI/CD pipelines (Docker, GitHub Actions)\n\n**What we offer**\n\n* **Competitive salary + equity:** Starting from A$100,000 base + Employee Share Options – you\'ll share in our success\n* **High-impact culture:** We have a *culture that ships* – we collaborate in person, move fast, and release often to stay ahead\n* **Career growth:** Grow with us – you\'ll take on more responsibility over time, learn from experienced tech leaders, and accelerate your development\n* **Modern tech & tools:** Work with the latest stack (React, Next.js, TypeScript, AI/ML APIs) and propose new tools – we love adopting best tech for the job\n* **Inclusive, fun team:** Join a friendly, diverse group that celebrates ideas and wins. We brainstorm over coffee, bond over team lunches, and enjoy a bit of banter\n* **Fast process:** No drawn-out interviews – our hiring process is quick and transparent, and we respect your time (expect feedback within days)\n\n**Our Tech Stack**\n\n* **Front-end:** React, Next.js, TypeScript, Tailwind CSS\n* **Back-end:** Node.js (serverless APIs), Python (for AI/ML services)\n* **AI/ML:** OpenAI GPT-4, LangChain, and other generative AI frameworks\n* **Infrastructure:** Everything Azure\n\n**About us**\n\n**Enterprise AI** is a Sydney-based startup on a mission to *improve the most important workflows and customer journeys for enterprise teams by embedding generative AI solutions* into daily operations. We\'re already making waves – our platform is in pilot with several large enterprise customers, and user feedback has been phenomenal. Our culture is casual, dynamic and fun: we work face-to-face at our Martin Place HQ, iterate relentlessly, and celebrate each win (game nights and team dinners included!). We\'re a tight-knit crew of ambitious, high-performing developers who believe in owning our work and building something game-changing together.\n\nSend your CV or LinkedIn profile to talent@enterpriseaigroup.com – we usually reply within 48 hours.',
    wage: 90000,
    wageInterval: 'yearly',
    stateAbbreviation: 'NSW',
    city: 'Sydney',
    isFeatured: false,
    locationRequirement: 'in-office',
    experienceLevel: 'junior',
    status: 'published',
    type: 'full-time',
    postedAt: '2025-07-27 14:02:06.721+00',
    createdAt: '2025-07-27 14:02:03.560272+00',
    updatedAt: '2025-07-27 14:02:06.722+00'
  },
  {
    id: 'a07a902b-14af-4d45-a9e1-81a906a299c7',
    organizationId: 'org_30SdGqAliowJDUBi3Gfy1z3Nbxx',
    title: 'Head of Engineering',
    description: 'You\'re a senior developer at heart, fluent in **Python** and **JavaScript/TypeScript** – and you still love to code. You can dive into a Python backend or a Node/TypeScript frontend (we use FastAPI and Next.js) and solve problems alongside your team. Your code reviews are legendary for spotting edge cases and elevating quality.\n\nAs Head of Engineering at Enterprise Ai, you will lead a talented team of engineers to deliver innovative AI solutions that drive the company\'s growth and success. This is a full-time position based in our Sydney, NSW office. You will be responsible for the overall technical direction and execution of our product roadmap, ensuring the delivery of high-quality, scalable and secure software systems.\n\n**What you\'ll be doing**\n\n* Provide strategic and technical leadership to the engineering team, setting the technical vision and establishing best practices\n* Manage the design, development and deployment of enterprise-grade AI solutions\n* Oversee the software development lifecycle, including planning, resource allocation, and process improvement\n* Foster an onsite culture of collaboration, innovation and continuous learning within the engineering team. The Gen AI world is moving fast, scheduled meetings are a fallback option, we need to meet, align, and get moving again, over a coffee, at lunch, or just by shouting over the floor\n* Identify and mitigate technical risks, ensuring the reliability and performance of our systems\n* Work closely with Product, Design and other cross-functional teams to deliver exceptional customer experiences\n* Mentor and develop the engineering team, supporting their growth and career progression\n* Champion engineering excellence and ensure adherence to coding standards and best practices\n\n**What we\'re looking for**\n\n* **8+ yrs software engineering, 3+ yrs leading teams, with a passion for fostering a culture of innovation, collaboration and continuous improvement**\n* Proven track record of leading and scaling high-performing engineering teams\n* Extensive experience in the design and development of complex, distributed software systems, potentially a proven record of building, deploying, and operating PaaS/SaaS at scale.\n* Proficiency in modern software engineering practices, including agile methodologies, DevOps, CICDand cloud-based architectures\n* Deep Python + JS/TS skills, cloud‑native skills on Azure (or AWS/GCP), frameworks and tools used in AI and software development\n* Excellent communication and stakeholder management skills, with the ability to translate technical concepts to all\n* Demonstrated problem-solving and decision-making skills, with a focus on delivering results. You want to work and drive an iterative, agile culture, fast, transparent, zero red tape—ideas on Monday, prototypes by Friday, and testing MVPs with customers as quickly as possible\n\n**What we offer**\n\nAt Enterprise Ai, we are committed to providing a rewarding and fulfilling work environment for our employees. Some of the key benefits we offer include:\n\n* Competitive salary and Employee Share Options Program\n* Employee Value Proposition, including, generous learning and development opportunities, and wellness\n* A diverse and inclusive workplace with opportunities for career growth, as we grow, the opportunities will\n* Team-building activities and social events to foster collaboration and camaraderie\n\n**About us**\n\nEnterprise Ai is a leading provider of innovative AI solutions that help organisations unlock the power of their data. Our mission is to revolutionise the way businesses operate through the transformative power of artificial intelligence. With a team of passionate and talented individuals, we are dedicated to pushing the boundaries of what\'s possible in the world of Generative AI.\n\nIf you\'re excited about the prospect of leading our engineering team and contributing to the growth of Enterprise Ai, we\'d love to hear from you. **Apply now** to join our dynamic and innovative company.\n\nSend your CV or LinkedIn profile to **talent@enterpriseaigroup.com** – we usually reply within 48 hours.',
    wage: 150000,
    wageInterval: 'yearly',
    stateAbbreviation: 'NSW',
    city: 'Sydney',
    isFeatured: false,
    locationRequirement: 'in-office',
    experienceLevel: 'junior',
    status: 'published',
    type: 'full-time',
    postedAt: '2025-07-27 14:02:31.302+00',
    createdAt: '2025-07-27 14:02:28.407373+00',
    updatedAt: '2025-07-27 14:02:31.302+00'
  },
  {
    id: '2b77922d-57eb-49e4-a698-75ef1eced013',
    organizationId: 'org_30SdxR9rZGkcQg26tgomARv7Cvv',
    title: 'Shopify Web Designer – CRO & UX/UI Specialist',
    description: '**Rate:** $50/hour (or fixed project rate for key pages)\n\n**Commitment:** Project-based, with ongoing work (1–2 landing pages/week)\n\n**Location:** Remote\n\n**Start:** ASAP\n\nAbout Us\n\nWe\'re a health venture studio launching **Shopify-based brands** across women\'s health, supplements, keto diets, hangover prevention, pet wellness, and more.\n\nWe\'re seeking a **high-converting landing page expert** who can take a brief, understand the customer journey, and design pages that are **clean, fast, beautiful, and built to convert**.\n\nWhat You\'ll Be Doing\n\n* Design **conversion-optimised landing pages** in Shopify (via Replo, GemPages, Shogun, or native theme builder)\n* Create pages for quizzes, product bundles, lead magnets, and upsells\n* Apply UX principles to reduce friction and boost AOV, CVR, and retention\n* Collaborate with our copywriters, funnel strategist, and Klaviyo/email team\n* Deliver fast, mobile-optimised designs with a clear visual hierarchy and CTA strategy\n* Optional: Figma mockups or direct build inside Shopify (we prefer Replo)\n\nIdeal Skills & Experience\n\n* 3+ years designing **Shopify product and landing pages**\n* Proven track record of increasing **conversion rates and reducing bounce**\n* Tools: Shopify, Replo (preferred), Shogun, PageFly, Figma\n* Strong understanding of **UX/UI best practices**, ecommerce psychology, and mobile-first design\n* Bonus: Experience in **health, wellness, or supplement** niches\n* Bonus: Able to troubleshoot Shopify theme code or CSS for speed/UX fixes\n\nYou Are\n\n* Detail-obsessed with a strong eye for clean, modern aesthetics\n* Skilled in **building pages that SELL**, not just look good\n* A clear communicator who takes initiative and meets deadlines\n* Able to juggle **multiple brands/projects** while keeping quality high',
    wage: 50,
    wageInterval: 'hourly',
    stateAbbreviation: 'SA',
    city: 'Adelaide',
    isFeatured: false,
    locationRequirement: 'in-office',
    experienceLevel: 'junior',
    status: 'published',
    type: 'full-time',
    postedAt: '2025-07-27 14:06:24.182+00',
    createdAt: '2025-07-27 14:06:20.638973+00',
    updatedAt: '2025-07-27 14:06:24.182+00'
  }
  // Continuing with remaining job listings...
] as const

export type JobListingFromBackup = typeof allJobListingsFromBackup[0]